version: "3.6"

services:
  server:
    environment:
      - DISABLE_ACCESS_TOKEN=true
    volumes:
      - ./volumes/imasdb:/home/imas/public/imasdb
      - ./volumes/cert:/home/imas/cert
      - ./volumes/server-properties:/home/imas/server-properties
    ports:
      - 8083:8083

  updateprocess:
    environment:
      - DISABLE_ACCESS_TOKEN=true
    volumes:
      - ./volumes/imasdb:/home/imas/public/imasdb

  watchdog:
    environment:
      - DISABLE_ACCESS_TOKEN=true
    volumes:
      - ./volumes/imasdb:/home/imas/public/imasdb
      - ./volumes/fair4fusion-docker-demo:/docker-entrypoint-properties.d

  react:
    environment:
      - MAIN_DOMAIN=localhost.dashboard-ui.pl
      - AUTH_CLIENT_ID=dashboard-ui-devel
      - AUTH_CLIENT_SECRET=3ef78bd2-029f-4d77-b8ec-102cc6361564
      - AUTH_OPENID_PROVIDER=
      - CATALOG_QT_API_URL=http://localhost:8080/
    ports:
      - 9100:9100
